import { describe, expect, it } from 'vitest';
import { generateSummary } from './summaryGenerator';
import { StoredLogMeta } from './logStore';

// Synthetic fixture exercising the full pipeline: nested CODE_UNIT/METHOD frames,
// SOQL with row counts, DML, an EXCEPTION_THROWN, a LIMIT_USAGE_FOR_NS block, and an
// untimestamped continuation line. Fictional names only.
const FIXTURE = [
  '43.0 APEX_CODE,FINEST;APEX_PROFILING,FINE;DB,FINEST',
  '16:00:00.0 (1000)|CODE_UNIT_STARTED|[EXTERNAL]|01q000000000001|Acme_Trigger on Account trigger event BeforeInsert|__sfdc_trigger/Acme_Trigger',
  '16:00:00.0 (2000)|METHOD_ENTRY|[10]|01p000000000001|AcmeController.doWork()',
  '16:00:00.0 (3000)|SOQL_EXECUTE_BEGIN|[12]|Aggregations:0|SELECT Id, Name FROM Account WHERE Name = \'a|b\'',
  '16:00:00.0 (5000)|SOQL_EXECUTE_END|[12]|Rows:3',
  '16:00:00.0 (6000)|DML_BEGIN|[15]|Op:Insert|Type:Account|Rows:2',
  '16:00:00.0 (7000)|DML_END|[15]',
  '16:00:00.0 (8000)|EXCEPTION_THROWN|[18]|System.NullPointerException: Attempt to de-reference a null object',
  'Class.AcmeController.doWork: line 18, column 1',
  '16:00:00.0 (9000)|METHOD_EXIT|[10]|01p000000000001|AcmeController.doWork()',
  '16:00:00.0 (10000)|LIMIT_USAGE_FOR_NS|(default)|',
  '  Number of SOQL queries: 1 out of 100',
  '  Number of DML statements: 1 out of 150',
  '  Number of DML rows: 2 out of 10000',
  '16:00:00.0 (11000)|CODE_UNIT_FINISHED|[EXTERNAL]|Acme_Trigger on Account trigger event BeforeInsert'
].join('\n');

const META: StoredLogMeta = {
  Id: '07L000000000001',
  Application: 'Unknown',
  DurationMilliseconds: 42,
  LogLength: 1234,
  LogUserId: '005000000000001',
  LogUserName: 'Test User',
  Operation: '/services/data',
  Status: 'Success',
  StartTime: '2026-01-01T16:00:00.000+0000',
  orgUsername: 'test@example.com',
  orgAlias: 'InzOrg',
  fetchedAt: '2026-01-01T00:00:00.000Z'
};

/** Strip the non-deterministic generated-at footer so the snapshot is stable. */
function normalize(md: string): string {
  return md.replace(/Generated by sf-log-reader on [^<]+\.<\/sub>/, 'Generated by sf-log-reader on <TS>.</sub>');
}

describe('summaryGenerator.generateSummary — behavior snapshot', () => {
  it('produces the full markdown summary for the synthetic fixture', () => {
    const md = normalize(generateSummary(META, FIXTURE));
    expect(md).toMatchInlineSnapshot(`
      "# Log Summary — \`07L000000000001\`

      | Field | Value |
      | --- | --- |
      | Org | \`InzOrg\` |
      | User | Test User (\`005000000000001\`) |
      | Operation | /services/data |
      | Application | Unknown |
      | Status | Success |
      | Reported duration | 42 ms |
      | Elapsed (from log) | 0.0 ms |
      | Log size | 1.2 KB |
      | Started at | 2026-01-01T16:00:00.000+0000 |
      | Fetched at | 2026-01-01T00:00:00.000Z |

      ## Event counts
      | Category | Count | Share |
      | --- | ---: | ---: |
      | SOQL | 2 | 20.0% |
      | DML | 2 | 20.0% |
      | CODE_UNIT | 2 | 20.0% |
      | METHOD | 2 | 20.0% |
      | EXCEPTION | 1 | 10.0% |
      | LIMITS | 1 | 10.0% |

      ## Observed counts (from log events)
      | Metric | Observed | Limit hit? |
      | --- | ---: | --- |
      | SOQL queries | 1 |  |
      | SOQL rows returned | 3 |  |
      | DML statements | 1 |  |
      | DML rows | 2 |  |

      ## Reported governor snapshot
      _Latest \`LIMIT_USAGE_FOR_NS\` snapshot SF emitted. This snapshot is written at frame boundaries, so it can lag the **Observed counts** above when the limit is hit inside a tight loop._

      | Metric | Used | Limit | Headroom | Usage |
      | --- | ---: | ---: | ---: | --- |
      | SOQL queries | 1 | 100 | 99 | ░░░░░░░░░░ 1.0% |
      | DML statements | 1 | 150 | 149 | ░░░░░░░░░░ 0.7% |
      | DML rows | 2 | 10000 | 9998 | ░░░░░░░░░░ 0.0% |

      ## Per-class breakdown
      | Class | Kind | Enters | SOQL | DML | Callouts | Exceptions | Time (ms) |
      | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |
      | AcmeController | class | 1 | 1 | 1 | 0 | 1 | 0.0 |
      | Acme_Trigger | trigger | 1 | 0 | 0 | 0 | 0 | 0.0 |

      ## DML breakdown
      | Op | Type | Statements | Rows |
      | --- | --- | ---: | ---: |
      | Insert | Account | 1 | 2 |

      ## Slowest SOQL queries
      | # | Line | Rows | Duration | Query |
      | ---: | --- | ---: | ---: | --- |
      | 1 | \`[12]\` | 3 | 0.0 ms | \`SELECT Id, Name FROM Account WHERE Name = 'a\\|b'\` |

      ## Hottest methods (by entry count)
      | Method | Calls |
      | --- | ---: |
      | \`AcmeController.doWork\` | 1 |

      ## Call graph

      \`\`\`mermaid
      %%{init: {"maxEdges": 400}}%%
      flowchart TD
        n0["AcmeController<br/>SOQL:1 DML:1 EXC:1<br/>0 ms"]
        class n0 hasExc;
        n1{{"Acme_Trigger<br/>0 ms<br/>(BeforeInsert on Account)"}}
        n1 --> n0
        classDef hasExc fill:#f85149,stroke:#7a1d24,color:#fff;
      \`\`\`

      ## Exceptions
      - **EXCEPTION_THROWN** \`[18]\` — System.NullPointerException: Attempt to de-reference a null object
      Class.AcmeController.doWork: line 18, column 1

      ## Top-level call order
      1. **Acme_Trigger** _(trigger, BeforeInsert on Account)_ — 0.0 ms

      <sub>Generated by sf-log-reader on <TS>.</sub>
      "
    `);
  });
});
