import { LogCategory, LogEntry, parseLogs, summarize } from './logParser';
import { StoredLogMeta } from './logStore';

interface Frame {
  id: number;
  parent: number | null;
  className: string;
  detail: string;
  enteredAt: string;
  exitedAt?: string;
  soql: number;
  dml: number;
  callouts: number;
  exceptions: string[];
  isTrigger: boolean;
}

interface ClassStats {
  className: string;
  soql: number;
  dml: number;
  callouts: number;
  exceptions: number;
  enters: number;
  isTrigger: boolean;
  detail: string;
}

interface SoqlSample {
  line: string;
  query: string;
  aggregations?: string;
  rows?: string;
}

const TRIGGER_EVENT_RE = /\btrigger event\b/i;
const CODE_UNIT_TRIGGER_RE = /^([^|]+?)\s+on\s+([^|]+?)\s+trigger event\s+([A-Za-z]+)/i;

export function generateSummary(meta: StoredLogMeta, body: string): string {
  const entries = parseLogs(body);
  const stats = summarize(entries);
  const { frames, byClass, mermaidEdges } = walk(entries);
  const topSoql = collectSoqlSamples(entries, 10);
  const exceptions = entries.filter(e => e.category === 'EXCEPTION');

  const lines: string[] = [];
  lines.push(`# Log Summary — \`${meta.Id}\``);
  lines.push('');
  lines.push(metadataBlock(meta, body));
  lines.push('');
  lines.push('## Event counts');
  lines.push(eventCountsTable(stats.byCategory));
  lines.push('');
  lines.push('## Per-class breakdown');
  lines.push(perClassTable(byClass));
  lines.push('');
  lines.push('## Call graph');
  lines.push('');
  lines.push(renderMermaid(byClass, mermaidEdges));
  lines.push('');
  if (topSoql.length > 0) {
    lines.push('## Top SOQL queries');
    for (const sample of topSoql) {
      const meta = [sample.line, sample.aggregations, sample.rows].filter(Boolean).join(' · ');
      lines.push(`- ${meta ? `\`${meta}\` — ` : ''}\`${truncate(sample.query, 200)}\``);
    }
    lines.push('');
  }
  if (exceptions.length > 0) {
    lines.push('## Exceptions');
    for (const e of exceptions) {
      lines.push(`- **${e.eventType}** ${e.lineRef ? `\`${e.lineRef}\`` : ''} — ${truncate(e.message, 400)}`);
    }
    lines.push('');
  }
  lines.push('## Top-level call order');
  lines.push(topLevelList(frames));
  lines.push('');
  lines.push(`<sub>Generated by sf-log-reader on ${new Date().toISOString()}.</sub>`);
  lines.push('');
  return lines.join('\n');
}

function walk(entries: LogEntry[]): {
  frames: Frame[];
  byClass: Map<string, ClassStats>;
  mermaidEdges: Map<string, Set<string>>;
} {
  const frames: Frame[] = [];
  const stack: number[] = [];
  const byClass = new Map<string, ClassStats>();
  const edges = new Map<string, Set<string>>();
  let nextId = 0;

  const ensureClassStats = (className: string, isTrigger: boolean, detail: string): ClassStats => {
    let s = byClass.get(className);
    if (!s) {
      s = { className, soql: 0, dml: 0, callouts: 0, exceptions: 0, enters: 0, isTrigger, detail };
      byClass.set(className, s);
    } else {
      if (isTrigger) s.isTrigger = true;
      if (detail && !s.detail) s.detail = detail;
    }
    return s;
  };

  const recordEdge = (parentId: number, childClass: string) => {
    const parent = frames[parentId];
    if (!parent) return;
    if (parent.className === childClass) return;
    let set = edges.get(parent.className);
    if (!set) {
      set = new Set();
      edges.set(parent.className, set);
    }
    set.add(childClass);
  };

  const push = (className: string, detail: string, enteredAt: string, isTrigger: boolean) => {
    const parent = stack.length > 0 ? stack[stack.length - 1] : null;
    const frame: Frame = {
      id: nextId++,
      parent,
      className,
      detail,
      enteredAt,
      soql: 0,
      dml: 0,
      callouts: 0,
      exceptions: [],
      isTrigger
    };
    frames.push(frame);
    stack.push(frame.id);
    const stats = ensureClassStats(className, isTrigger, detail);
    stats.enters += 1;
    if (parent != null) recordEdge(parent, className);
  };

  const pop = (exitedAt: string) => {
    const id = stack.pop();
    if (id == null) return;
    frames[id].exitedAt = exitedAt;
  };

  const top = (): Frame | undefined => (stack.length > 0 ? frames[stack[stack.length - 1]] : undefined);
  const attribute = (mut: (s: ClassStats, f: Frame) => void) => {
    const f = top();
    if (!f) return;
    const s = byClass.get(f.className);
    if (!s) return;
    mut(s, f);
  };

  for (const e of entries) {
    switch (e.eventType) {
      case 'CODE_UNIT_STARTED': {
        const parsed = parseCodeUnit(e);
        push(parsed.className, parsed.detail, e.timestamp, parsed.isTrigger);
        break;
      }
      case 'CODE_UNIT_FINISHED':
        pop(e.timestamp);
        break;
      case 'METHOD_ENTRY': {
        const parsed = parseMethod(e);
        push(parsed.className, parsed.detail, e.timestamp, false);
        break;
      }
      case 'METHOD_EXIT':
        pop(e.timestamp);
        break;
      case 'SOQL_EXECUTE_BEGIN':
        attribute((s, f) => { s.soql += 1; f.soql += 1; });
        break;
      case 'DML_BEGIN':
        attribute((s, f) => { s.dml += 1; f.dml += 1; });
        break;
      case 'CALLOUT_REQUEST':
        attribute((s, f) => { s.callouts += 1; f.callouts += 1; });
        break;
      case 'EXCEPTION_THROWN':
      case 'FATAL_ERROR':
        attribute((s, f) => { s.exceptions += 1; f.exceptions.push(e.message); });
        break;
    }
  }

  return { frames, byClass, mermaidEdges: edges };
}

function parseCodeUnit(entry: LogEntry): { className: string; detail: string; isTrigger: boolean } {
  const parts = entry.message.split(' | ').map(s => s.trim()).filter(Boolean);
  const candidate = parts[parts.length - 1] ?? '';
  if (TRIGGER_EVENT_RE.test(candidate)) {
    const m = candidate.match(CODE_UNIT_TRIGGER_RE);
    if (m) {
      return { className: m[1].trim(), detail: `${m[3]} on ${m[2].trim()}`, isTrigger: true };
    }
    const first = candidate.split(/\s+/)[0] ?? candidate;
    return { className: first, detail: candidate, isTrigger: true };
  }
  const dot = candidate.indexOf('.');
  if (dot > 0) {
    return { className: candidate.slice(0, dot), detail: candidate.slice(dot + 1), isTrigger: false };
  }
  return { className: candidate || '(anonymous)', detail: '', isTrigger: false };
}

function parseMethod(entry: LogEntry): { className: string; detail: string } {
  const parts = entry.message.split(' | ').map(s => s.trim()).filter(Boolean);
  const candidate = parts[parts.length - 1] ?? '';
  const parenIdx = candidate.indexOf('(');
  const signature = parenIdx >= 0 ? candidate.slice(0, parenIdx) : candidate;
  const dot = signature.lastIndexOf('.');
  if (dot > 0) {
    return { className: signature.slice(0, dot), detail: signature.slice(dot + 1) };
  }
  return { className: signature || '(anonymous)', detail: '' };
}

function metadataBlock(meta: StoredLogMeta, body: string): string {
  const rows: Array<[string, string]> = [
    ['Org', `\`${meta.orgAlias ?? meta.orgUsername}\``],
    ['User', `${meta.LogUserName ?? '?'} (\`${meta.LogUserId ?? '?'}\`)`],
    ['Operation', meta.Operation ?? '—'],
    ['Application', meta.Application ?? '—'],
    ['Status', meta.Status ?? '—'],
    ['Duration', meta.DurationMilliseconds != null ? `${meta.DurationMilliseconds} ms` : '—'],
    ['Log size', meta.LogLength != null ? formatBytes(meta.LogLength) : `${body.length} bytes (local)`],
    ['Started at', meta.StartTime ?? '—'],
    ['Fetched at', meta.fetchedAt]
  ];
  const out = ['| Field | Value |', '| --- | --- |'];
  for (const [k, v] of rows) out.push(`| ${k} | ${escapeMd(v)} |`);
  return out.join('\n');
}

function eventCountsTable(byCategory: Record<LogCategory, number>): string {
  const rows = (Object.entries(byCategory) as Array<[LogCategory, number]>)
    .filter(([, count]) => count > 0)
    .sort((a, b) => b[1] - a[1]);
  if (rows.length === 0) return '_No entries parsed._';
  const out = ['| Category | Count |', '| --- | ---: |'];
  for (const [cat, count] of rows) out.push(`| ${cat} | ${count} |`);
  return out.join('\n');
}

function perClassTable(byClass: Map<string, ClassStats>): string {
  if (byClass.size === 0) return '_No class/trigger frames detected._';
  const rows = Array.from(byClass.values()).sort((a, b) => {
    const total = (s: ClassStats) => s.soql + s.dml + s.callouts + s.exceptions;
    return total(b) - total(a) || a.className.localeCompare(b.className);
  });
  const out = ['| Class | Kind | Enters | SOQL | DML | Callouts | Exceptions |',
    '| --- | --- | ---: | ---: | ---: | ---: | ---: |'];
  for (const s of rows) {
    out.push(`| ${escapeMd(s.className)} | ${s.isTrigger ? 'trigger' : 'class'} | ${s.enters} | ${s.soql} | ${s.dml} | ${s.callouts} | ${s.exceptions} |`);
  }
  return out.join('\n');
}

function renderMermaid(byClass: Map<string, ClassStats>, edges: Map<string, Set<string>>): string {
  if (byClass.size === 0) return '_(no frames to diagram)_';
  const ids = new Map<string, string>();
  let counter = 0;
  for (const className of byClass.keys()) {
    ids.set(className, `n${counter++}`);
  }
  const lines = ['```mermaid', 'flowchart TD'];
  for (const stats of byClass.values()) {
    const id = ids.get(stats.className)!;
    const labelLines: string[] = [escapeMermaidLabel(stats.className)];
    const counts = [
      stats.soql ? `SOQL:${stats.soql}` : '',
      stats.dml ? `DML:${stats.dml}` : '',
      stats.callouts ? `HTTP:${stats.callouts}` : '',
      stats.exceptions ? `EXC:${stats.exceptions}` : ''
    ].filter(Boolean).join(' ');
    if (counts) labelLines.push(counts);
    if (stats.isTrigger && stats.detail) labelLines.push(`(${escapeMermaidLabel(stats.detail)})`);
    const shape = stats.isTrigger ? `${id}{{"${labelLines.join('<br/>')}"}}` : `${id}["${labelLines.join('<br/>')}"]`;
    lines.push(`  ${shape}`);
    if (stats.exceptions > 0) lines.push(`  class ${id} hasExc;`);
  }
  for (const [from, tos] of edges.entries()) {
    const fromId = ids.get(from);
    if (!fromId) continue;
    for (const to of tos) {
      const toId = ids.get(to);
      if (!toId) continue;
      lines.push(`  ${fromId} --> ${toId}`);
    }
  }
  lines.push('  classDef hasExc fill:#f85149,stroke:#7a1d24,color:#fff;');
  lines.push('```');
  return lines.join('\n');
}

function collectSoqlSamples(entries: LogEntry[], limit: number): SoqlSample[] {
  const out: SoqlSample[] = [];
  for (const e of entries) {
    if (e.eventType !== 'SOQL_EXECUTE_BEGIN') continue;
    const segments = e.message.split(' | ').map(s => s.trim());
    let aggregations: string | undefined;
    let query = segments[segments.length - 1] ?? '';
    if (segments[0] && /^Aggregations:/i.test(segments[0])) {
      aggregations = segments[0];
      if (segments.length > 1) query = segments[segments.length - 1];
    }
    out.push({ line: e.lineRef, query, aggregations });
    if (out.length >= limit) break;
  }
  return out;
}

function topLevelList(frames: Frame[]): string {
  const tops = frames.filter(f => f.parent == null);
  if (tops.length === 0) return '_No top-level frames detected._';
  return tops
    .map((f, i) => {
      const counts = [
        f.soql ? `${f.soql} SOQL` : '',
        f.dml ? `${f.dml} DML` : '',
        f.callouts ? `${f.callouts} callouts` : '',
        f.exceptions.length ? `${f.exceptions.length} exceptions` : ''
      ].filter(Boolean).join(', ');
      const tag = f.isTrigger ? 'trigger' : 'class';
      return `${i + 1}. **${escapeMd(f.className)}** _(${tag}${f.detail ? `, ${escapeMd(f.detail)}` : ''})_${counts ? ` — ${counts}` : ''}`;
    })
    .join('\n');
}

function truncate(s: string, max: number): string {
  if (!s) return '';
  if (s.length <= max) return s;
  return s.slice(0, max) + '…';
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function escapeMermaidLabel(s: string): string {
  return s.replace(/"/g, '\\"').replace(/[\r\n]+/g, ' ');
}
