import { LogCategory, LogEntry, parseLogs, summarize } from './logParser';
import { StoredLogMeta } from './logStore';

interface Frame {
  id: number;
  parent: number | null;
  className: string;
  detail: string;
  enteredAt: string;
  enteredNanos: number | null;
  exitedNanos: number | null;
  soql: number;
  dml: number;
  callouts: number;
  exceptions: string[];
  isTrigger: boolean;
}

interface ClassStats {
  className: string;
  soql: number;
  dml: number;
  callouts: number;
  exceptions: number;
  enters: number;
  totalNanos: number;
  isTrigger: boolean;
  detail: string;
}

interface SoqlTiming {
  lineRef: string;
  query: string;
  rows?: number;
  aggregations?: string;
  durationMs?: number;
}

interface DmlOp {
  op: string;
  type: string;
  count: number;
  rows: number;
}

interface MethodCount {
  signature: string;
  enters: number;
}

interface LimitMetric {
  name: string;
  used: number;
  max: number;
}

const TRIGGER_EVENT_RE = /\btrigger event\b/i;
const CODE_UNIT_TRIGGER_RE = /^([^|]+?)\s+on\s+([^|]+?)\s+trigger event\s+([A-Za-z]+)/i;

export interface SummaryOptions {
  mermaidMaxEdges?: number;
  mermaidMaxNodes?: number;
}

interface ObservedCounts {
  soqlQueries: number;
  soqlRows: number;
  soslQueries: number;
  dmlStatements: number;
  dmlRows: number;
  callouts: number;
  asyncJobsEnqueued: number;
  publishImmediateEvents: number;
}

interface LimitException {
  message: string;
  metric?: string;
  value?: number;
  cap?: number;
  lineRef: string;
}

export function generateSummary(meta: StoredLogMeta, body: string, options: SummaryOptions = {}): string {
  const entries = parseLogs(body);
  const stats = summarize(entries);
  const { frames, byClass, edgeCalls } = walk(entries);
  const soqlTimings = collectSoqlTimings(entries);
  const dmlBreakdown = collectDmlBreakdown(entries);
  const hottestMethods = collectHottestMethods(entries, 15);
  const observed = collectObservedCounts(entries, soqlTimings, dmlBreakdown);
  const limits = parseLimits(body);
  const exceptions = entries.filter(e => e.category === 'EXCEPTION');
  const limitExceptions = collectLimitExceptions(entries);
  const totalElapsedMs = computeTotalElapsedMs(entries);

  const lines: string[] = [];
  lines.push(`# Log Summary — \`${meta.Id}\``);
  lines.push('');
  lines.push(metadataBlock(meta, body, totalElapsedMs));
  lines.push('');
  lines.push('## Event counts');
  lines.push(eventCountsTable(stats.byCategory, stats.total));
  lines.push('');
  if (limitExceptions.length > 0) {
    lines.push('## Limit exceptions');
    for (const le of limitExceptions) {
      const at = le.metric && le.value != null && le.cap != null
        ? ` — hit at **${le.value}/${le.cap}** ${escapeMd(le.metric)}`
        : '';
      lines.push(`- \`${escapeMd(le.lineRef)}\` ${escapeMd(le.message)}${at}`);
    }
    lines.push('');
  }
  lines.push('## Observed counts (from log events)');
  lines.push(observedCountsTable(observed, limitExceptions));
  lines.push('');
  if (limits.length > 0) {
    lines.push('## Reported governor snapshot');
    lines.push('_Latest `LIMIT_USAGE_FOR_NS` snapshot SF emitted. This snapshot is written at frame boundaries, so it can lag the **Observed counts** above when the limit is hit inside a tight loop._');
    lines.push('');
    lines.push(limitsTable(limits));
    lines.push('');
  }
  lines.push('## Per-class breakdown');
  lines.push(perClassTable(byClass));
  lines.push('');
  if (dmlBreakdown.length > 0) {
    lines.push('## DML breakdown');
    lines.push(dmlBreakdownTable(dmlBreakdown));
    lines.push('');
  }
  if (soqlTimings.length > 0) {
    lines.push('## Slowest SOQL queries');
    lines.push(soqlTimingTable(soqlTimings.slice(0, 10)));
    lines.push('');
  }
  if (hottestMethods.length > 0) {
    lines.push('## Hottest methods (by entry count)');
    lines.push(hottestMethodsTable(hottestMethods));
    lines.push('');
  }
  lines.push('## Call graph');
  lines.push('');
  lines.push(renderMermaid(byClass, edgeCalls, {
    maxEdges: options.mermaidMaxEdges,
    maxNodes: options.mermaidMaxNodes
  }));
  lines.push('');
  if (exceptions.length > 0) {
    lines.push('## Exceptions');
    for (const e of exceptions) {
      lines.push(`- **${e.eventType}** ${e.lineRef ? `\`${e.lineRef}\`` : ''} — ${truncate(e.message, 400)}`);
    }
    lines.push('');
  }
  lines.push('## Top-level call order');
  lines.push(topLevelList(frames));
  lines.push('');
  lines.push(`<sub>Generated by sf-log-reader on ${new Date().toISOString()}.</sub>`);
  lines.push('');
  return lines.join('\n');
}

function walk(entries: LogEntry[]): {
  frames: Frame[];
  byClass: Map<string, ClassStats>;
  edgeCalls: Map<string, Map<string, number>>;
} {
  const frames: Frame[] = [];
  const stack: number[] = [];
  const byClass = new Map<string, ClassStats>();
  const edgeCalls = new Map<string, Map<string, number>>();
  let nextId = 0;

  const ensureClassStats = (className: string, isTrigger: boolean, detail: string): ClassStats => {
    let s = byClass.get(className);
    if (!s) {
      s = { className, soql: 0, dml: 0, callouts: 0, exceptions: 0, enters: 0, totalNanos: 0, isTrigger, detail };
      byClass.set(className, s);
    } else {
      if (isTrigger) s.isTrigger = true;
      if (detail && !s.detail) s.detail = detail;
    }
    return s;
  };

  const recordEdge = (parentId: number, childClass: string) => {
    const parent = frames[parentId];
    if (!parent || parent.className === childClass) return;
    let map = edgeCalls.get(parent.className);
    if (!map) {
      map = new Map();
      edgeCalls.set(parent.className, map);
    }
    map.set(childClass, (map.get(childClass) ?? 0) + 1);
  };

  const push = (className: string, detail: string, entry: LogEntry, isTrigger: boolean) => {
    const parent = stack.length > 0 ? stack[stack.length - 1] : null;
    const frame: Frame = {
      id: nextId++,
      parent,
      className,
      detail,
      enteredAt: entry.timestamp,
      enteredNanos: entry.timestampNanos,
      exitedNanos: null,
      soql: 0,
      dml: 0,
      callouts: 0,
      exceptions: [],
      isTrigger
    };
    frames.push(frame);
    stack.push(frame.id);
    const stats = ensureClassStats(className, isTrigger, detail);
    stats.enters += 1;
    if (parent != null) recordEdge(parent, className);
  };

  const pop = (entry: LogEntry) => {
    const id = stack.pop();
    if (id == null) return;
    const frame = frames[id];
    frame.exitedNanos = entry.timestampNanos;
    if (frame.enteredNanos != null && frame.exitedNanos != null) {
      const dur = frame.exitedNanos - frame.enteredNanos;
      if (dur > 0) {
        const stats = byClass.get(frame.className);
        if (stats) stats.totalNanos += dur;
      }
    }
  };

  const top = (): Frame | undefined => (stack.length > 0 ? frames[stack[stack.length - 1]] : undefined);
  const attribute = (mut: (s: ClassStats, f: Frame) => void) => {
    const f = top();
    if (!f) return;
    const s = byClass.get(f.className);
    if (!s) return;
    mut(s, f);
  };

  for (const e of entries) {
    switch (e.eventType) {
      case 'CODE_UNIT_STARTED': {
        const parsed = parseCodeUnit(e);
        push(parsed.className, parsed.detail, e, parsed.isTrigger);
        break;
      }
      case 'CODE_UNIT_FINISHED':
        pop(e);
        break;
      case 'METHOD_ENTRY': {
        const parsed = parseMethod(e);
        push(parsed.className, parsed.detail, e, false);
        break;
      }
      case 'METHOD_EXIT':
        pop(e);
        break;
      case 'SOQL_EXECUTE_BEGIN':
        attribute((s, f) => { s.soql += 1; f.soql += 1; });
        break;
      case 'DML_BEGIN':
        attribute((s, f) => { s.dml += 1; f.dml += 1; });
        break;
      case 'CALLOUT_REQUEST':
        attribute((s, f) => { s.callouts += 1; f.callouts += 1; });
        break;
      case 'EXCEPTION_THROWN':
      case 'FATAL_ERROR':
        attribute((s, f) => { s.exceptions += 1; f.exceptions.push(e.message); });
        break;
    }
  }

  return { frames, byClass, edgeCalls };
}

function parseCodeUnit(entry: LogEntry): { className: string; detail: string; isTrigger: boolean } {
  const parts = entry.message.split(' | ').map(s => s.trim()).filter(Boolean);
  const candidate = parts[parts.length - 1] ?? '';
  if (TRIGGER_EVENT_RE.test(candidate)) {
    const m = candidate.match(CODE_UNIT_TRIGGER_RE);
    if (m) return { className: m[1].trim(), detail: `${m[3]} on ${m[2].trim()}`, isTrigger: true };
    const first = candidate.split(/\s+/)[0] ?? candidate;
    return { className: first, detail: candidate, isTrigger: true };
  }
  const dot = candidate.indexOf('.');
  if (dot > 0) return { className: candidate.slice(0, dot), detail: candidate.slice(dot + 1), isTrigger: false };
  return { className: candidate || '(anonymous)', detail: '', isTrigger: false };
}

function parseMethod(entry: LogEntry): { className: string; detail: string } {
  const parts = entry.message.split(' | ').map(s => s.trim()).filter(Boolean);
  const candidate = parts[parts.length - 1] ?? '';
  const parenIdx = candidate.indexOf('(');
  const signature = parenIdx >= 0 ? candidate.slice(0, parenIdx) : candidate;
  const dot = signature.lastIndexOf('.');
  if (dot > 0) return { className: signature.slice(0, dot), detail: signature.slice(dot + 1) };
  return { className: signature || '(anonymous)', detail: '' };
}

function collectObservedCounts(entries: LogEntry[], soqlTimings: SoqlTiming[], dmlBreakdown: DmlOp[]): ObservedCounts {
  const counts: ObservedCounts = {
    soqlQueries: 0,
    soqlRows: 0,
    soslQueries: 0,
    dmlStatements: 0,
    dmlRows: 0,
    callouts: 0,
    asyncJobsEnqueued: 0,
    publishImmediateEvents: 0
  };
  for (const e of entries) {
    switch (e.eventType) {
      case 'SOQL_EXECUTE_BEGIN': counts.soqlQueries += 1; break;
      case 'SOSL_EXECUTE_BEGIN': counts.soslQueries += 1; break;
      case 'DML_BEGIN': counts.dmlStatements += 1; break;
      case 'CALLOUT_REQUEST': counts.callouts += 1; break;
      case 'EVENT_SERVICE_PUB_DETAIL': counts.publishImmediateEvents += 1; break;
      case 'ASYNC_OPERATION_INSERTED': counts.asyncJobsEnqueued += 1; break;
    }
  }
  for (const t of soqlTimings) if (t.rows != null) counts.soqlRows += t.rows;
  for (const d of dmlBreakdown) counts.dmlRows += d.rows;
  return counts;
}

function collectLimitExceptions(entries: LogEntry[]): LimitException[] {
  const out: LimitException[] = [];
  const seen = new Set<string>();
  for (const e of entries) {
    if (e.eventType !== 'EXCEPTION_THROWN' && e.eventType !== 'FATAL_ERROR') continue;
    if (!/LimitException/i.test(e.message)) continue;
    const dedupeKey = `${e.lineRef}|${e.message.trim()}`;
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);
    // Strip the "System.LimitException:" prefix, then peel off an optional "<metric>: <value>[ out of <cap>]" tail.
    const stripped = e.message.replace(/^.*?LimitException:\s*/i, '').trim();
    const m = stripped.match(/^(.+?)(?::\s*(\d+)(?:\s+out of\s+(\d+))?)?\s*$/i);
    if (m) {
      out.push({
        message: e.message,
        metric: m[1].trim(),
        value: m[2] ? Number(m[2]) : undefined,
        cap: m[3] ? Number(m[3]) : undefined,
        lineRef: e.lineRef
      });
    } else {
      out.push({ message: e.message, lineRef: e.lineRef });
    }
  }
  return out;
}

function observedCountsTable(c: ObservedCounts, limitExceptions: LimitException[]): string {
  const exMap = new Map<string, LimitException>();
  for (const le of limitExceptions) if (le.metric) exMap.set(le.metric.toLowerCase(), le);
  const lookup = (...keys: string[]) => {
    for (const k of keys) {
      for (const [name, le] of exMap.entries()) if (name.includes(k)) return le;
    }
    return undefined;
  };
  const rows: Array<[string, number, LimitException | undefined]> = [
    ['SOQL queries', c.soqlQueries, lookup('soql queries', 'soql')],
    ['SOQL rows returned', c.soqlRows, lookup('query rows')],
    ['SOSL queries', c.soslQueries, lookup('sosl')],
    ['DML statements', c.dmlStatements, lookup('dml statements')],
    ['DML rows', c.dmlRows, lookup('dml rows')],
    ['Callouts', c.callouts, lookup('callout')],
    ['Async jobs enqueued', c.asyncJobsEnqueued, lookup('async')],
    ['Platform events published', c.publishImmediateEvents, undefined]
  ];
  const visible = rows.filter(([, v, ex]) => v > 0 || ex);
  if (visible.length === 0) return '_No countable events observed._';
  const out = ['| Metric | Observed | Limit hit? |', '| --- | ---: | --- |'];
  for (const [name, value, ex] of visible) {
    const flag = ex
      ? `❌ exceeded${ex.cap != null ? ` (\`${ex.value ?? '?'}/${ex.cap}\`)` : ex.value != null ? ` (at \`${ex.value}\`)` : ''}`
      : '';
    out.push(`| ${escapeMd(name)} | ${value} | ${flag} |`);
  }
  return out.join('\n');
}

function collectSoqlTimings(entries: LogEntry[]): SoqlTiming[] {
  const stack: Array<{ index: number; entry: LogEntry; query: string; aggregations?: string }> = [];
  const out: SoqlTiming[] = [];
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    if (e.eventType === 'SOQL_EXECUTE_BEGIN') {
      const segments = e.message.split(' | ').map(s => s.trim()).filter(Boolean);
      let aggregations: string | undefined;
      let query = segments[segments.length - 1] ?? '';
      if (segments[0] && /^Aggregations:/i.test(segments[0])) {
        aggregations = segments[0];
        if (segments.length > 1) query = segments[segments.length - 1];
      }
      stack.push({ index: i, entry: e, query, aggregations });
    } else if (e.eventType === 'SOQL_EXECUTE_END') {
      const open = stack.pop();
      if (!open) continue;
      const segments = e.message.split(' | ').map(s => s.trim()).filter(Boolean);
      const rowsField = segments.find(s => /^Rows:/i.test(s));
      const rows = rowsField ? Number(rowsField.replace(/^Rows:/i, '')) : undefined;
      const durationMs =
        open.entry.timestampNanos != null && e.timestampNanos != null
          ? Math.max(0, (e.timestampNanos - open.entry.timestampNanos) / 1_000_000)
          : undefined;
      out.push({
        lineRef: open.entry.lineRef,
        query: open.query,
        aggregations: open.aggregations,
        rows: Number.isFinite(rows) ? rows : undefined,
        durationMs
      });
    }
  }
  return out.sort((a, b) => (b.durationMs ?? 0) - (a.durationMs ?? 0));
}

function collectDmlBreakdown(entries: LogEntry[]): DmlOp[] {
  const bucket = new Map<string, DmlOp>();
  for (const e of entries) {
    if (e.eventType !== 'DML_BEGIN') continue;
    const segments = e.message.split(' | ').map(s => s.trim());
    const op = (segments.find(s => /^Op:/i.test(s)) ?? 'Op:Unknown').replace(/^Op:/i, '');
    const type = (segments.find(s => /^Type:/i.test(s)) ?? 'Type:?').replace(/^Type:/i, '');
    const rowsField = segments.find(s => /^Rows:/i.test(s));
    const rows = rowsField ? Number(rowsField.replace(/^Rows:/i, '')) : 0;
    const key = `${op} ${type}`;
    const cur = bucket.get(key) ?? { op, type, count: 0, rows: 0 };
    cur.count += 1;
    cur.rows += Number.isFinite(rows) ? rows : 0;
    bucket.set(key, cur);
  }
  return Array.from(bucket.values()).sort((a, b) => b.rows - a.rows || b.count - a.count);
}

function collectHottestMethods(entries: LogEntry[], limit: number): MethodCount[] {
  const counts = new Map<string, number>();
  for (const e of entries) {
    if (e.eventType !== 'METHOD_ENTRY') continue;
    const segs = e.message.split(' | ').map(s => s.trim()).filter(Boolean);
    const candidate = segs[segs.length - 1] ?? '';
    const sig = candidate.replace(/\(.*$/, '').trim();
    if (!sig) continue;
    counts.set(sig, (counts.get(sig) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .map(([signature, enters]) => ({ signature, enters }))
    .sort((a, b) => b.enters - a.enters)
    .slice(0, limit);
}

function parseLimits(raw: string): LimitMetric[] {
  if (!raw) return [];
  const lines = raw.split('\n');
  let inBlock = false;
  const latest = new Map<string, LimitMetric>();
  for (const rawLine of lines) {
    const line = rawLine.replace(/\r$/, '');
    if (line.includes('|LIMIT_USAGE_FOR_NS|') || /^LIMIT_USAGE_FOR_NS\|/.test(line.trim())) {
      inBlock = true;
      continue;
    }
    if (!inBlock) continue;
    const trimmed = line.trim();
    if (!trimmed) { inBlock = false; continue; }
    if (/^\d{2}:\d{2}:\d{2}/.test(trimmed)) { inBlock = false; continue; }
    const m = trimmed.match(/^(.+?):\s*(\d+)\s+out of\s+(\d+)/i);
    if (m) {
      const name = m[1].replace(/^Number of\s+/i, '').trim();
      latest.set(name, { name, used: Number(m[2]), max: Number(m[3]) });
    }
  }
  return Array.from(latest.values()).sort((a, b) => percent(b) - percent(a));
}

function percent(m: LimitMetric): number {
  return m.max > 0 ? m.used / m.max : 0;
}

function computeTotalElapsedMs(entries: LogEntry[]): number | undefined {
  const first = entries.find(e => e.timestampNanos != null);
  const last = [...entries].reverse().find(e => e.timestampNanos != null);
  if (!first || !last || first === last) return undefined;
  return Math.max(0, ((last.timestampNanos ?? 0) - (first.timestampNanos ?? 0)) / 1_000_000);
}

function metadataBlock(meta: StoredLogMeta, body: string, totalElapsedMs: number | undefined): string {
  const rows: Array<[string, string]> = [
    ['Org', `\`${meta.orgAlias ?? meta.orgUsername}\``],
    ['User', `${meta.LogUserName ?? '?'} (\`${meta.LogUserId ?? '?'}\`)`],
    ['Operation', meta.Operation ?? '—'],
    ['Application', meta.Application ?? '—'],
    ['Status', meta.Status ?? '—'],
    ['Reported duration', meta.DurationMilliseconds != null ? `${meta.DurationMilliseconds} ms` : '—'],
    ['Elapsed (from log)', totalElapsedMs != null ? `${totalElapsedMs.toFixed(1)} ms` : '—'],
    ['Log size', meta.LogLength != null ? formatBytes(meta.LogLength) : `${body.length} bytes (local)`],
    ['Started at', meta.StartTime ?? '—'],
    ['Fetched at', meta.fetchedAt]
  ];
  const out = ['| Field | Value |', '| --- | --- |'];
  for (const [k, v] of rows) out.push(`| ${k} | ${escapeMd(v)} |`);
  return out.join('\n');
}

function eventCountsTable(byCategory: Record<LogCategory, number>, total: number): string {
  const rows = (Object.entries(byCategory) as Array<[LogCategory, number]>)
    .filter(([, count]) => count > 0)
    .sort((a, b) => b[1] - a[1]);
  if (rows.length === 0) return '_No entries parsed._';
  const out = ['| Category | Count | Share |', '| --- | ---: | ---: |'];
  for (const [cat, count] of rows) {
    const pct = total > 0 ? ((count / total) * 100).toFixed(1) : '0.0';
    out.push(`| ${cat} | ${count} | ${pct}% |`);
  }
  return out.join('\n');
}

function limitsTable(limits: LimitMetric[]): string {
  const out = ['| Metric | Used | Limit | Headroom | Usage |', '| --- | ---: | ---: | ---: | --- |'];
  for (const m of limits) {
    const pct = m.max > 0 ? (m.used / m.max) * 100 : 0;
    const bar = pctBar(pct);
    const headroom = m.max - m.used;
    out.push(`| ${escapeMd(m.name)} | ${m.used} | ${m.max} | ${headroom} | ${bar} ${pct.toFixed(1)}% |`);
  }
  return out.join('\n');
}

function pctBar(pct: number): string {
  const slots = 10;
  const filled = Math.min(slots, Math.round((pct / 100) * slots));
  return '█'.repeat(filled) + '░'.repeat(slots - filled);
}

function perClassTable(byClass: Map<string, ClassStats>): string {
  if (byClass.size === 0) return '_No class/trigger frames detected._';
  const rows = Array.from(byClass.values()).sort((a, b) => {
    const total = (s: ClassStats) => s.soql + s.dml + s.callouts + s.exceptions;
    return total(b) - total(a) || a.className.localeCompare(b.className);
  });
  const out = ['| Class | Kind | Enters | SOQL | DML | Callouts | Exceptions | Time (ms) |',
    '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |'];
  for (const s of rows) {
    const time = s.totalNanos > 0 ? (s.totalNanos / 1_000_000).toFixed(1) : '—';
    out.push(`| ${escapeMd(s.className)} | ${s.isTrigger ? 'trigger' : 'class'} | ${s.enters} | ${s.soql} | ${s.dml} | ${s.callouts} | ${s.exceptions} | ${time} |`);
  }
  return out.join('\n');
}

function dmlBreakdownTable(rows: DmlOp[]): string {
  const out = ['| Op | Type | Statements | Rows |', '| --- | --- | ---: | ---: |'];
  for (const r of rows) {
    out.push(`| ${escapeMd(r.op)} | ${escapeMd(r.type)} | ${r.count} | ${r.rows} |`);
  }
  return out.join('\n');
}

function soqlTimingTable(rows: SoqlTiming[]): string {
  const out = ['| # | Line | Rows | Duration | Query |', '| ---: | --- | ---: | ---: | --- |'];
  rows.forEach((r, i) => {
    const dur = r.durationMs != null ? `${r.durationMs.toFixed(1)} ms` : '—';
    const rows = r.rows != null ? String(r.rows) : '—';
    out.push(`| ${i + 1} | \`${escapeMd(r.lineRef)}\` | ${rows} | ${dur} | \`${escapeMd(truncate(r.query, 160))}\` |`);
  });
  return out.join('\n');
}

function hottestMethodsTable(methods: MethodCount[]): string {
  const out = ['| Method | Calls |', '| --- | ---: |'];
  for (const m of methods) out.push(`| \`${escapeMd(m.signature)}\` | ${m.enters} |`);
  return out.join('\n');
}

interface MermaidOptions {
  maxEdges?: number;
  maxNodes?: number;
}

function renderMermaid(byClass: Map<string, ClassStats>, edgeCalls: Map<string, Map<string, number>>, options: MermaidOptions = {}): string {
  if (byClass.size === 0) return '_(no frames to diagram)_';
  const maxNodes = Math.max(1, options.maxNodes ?? 60);
  const maxEdges = Math.max(1, options.maxEdges ?? 400);

  // Rank classes by activity so we drop the least useful first.
  const activity = (s: ClassStats) =>
    s.enters + s.soql * 2 + s.dml * 2 + s.exceptions * 3 + s.callouts * 2;
  const ranked = Array.from(byClass.values()).sort((a, b) => activity(b) - activity(a));
  const totalNodes = ranked.length;
  const keptNodes = ranked.slice(0, maxNodes);
  const droppedNodes = totalNodes - keptNodes.length;
  const kept = new Set(keptNodes.map(s => s.className));

  // Flatten edges (only between kept nodes), rank by call count desc.
  type EdgeRec = { from: string; to: string; count: number };
  const allEdges: EdgeRec[] = [];
  for (const [from, tos] of edgeCalls.entries()) {
    if (!kept.has(from)) continue;
    for (const [to, count] of tos.entries()) {
      if (!kept.has(to)) continue;
      allEdges.push({ from, to, count });
    }
  }
  allEdges.sort((a, b) => b.count - a.count);
  const keptEdges = allEdges.slice(0, maxEdges);
  const droppedEdges = allEdges.length - keptEdges.length;

  const ids = new Map<string, string>();
  let counter = 0;
  for (const s of keptNodes) ids.set(s.className, `n${counter++}`);

  const lines: string[] = ['```mermaid'];
  if (maxEdges > 0) lines.push(`%%{init: {"maxEdges": ${maxEdges}}}%%`);
  lines.push('flowchart TD');
  for (const stats of keptNodes) {
    const id = ids.get(stats.className)!;
    const labelLines: string[] = [escapeMermaidLabel(stats.className)];
    const counts = [
      stats.soql ? `SOQL:${stats.soql}` : '',
      stats.dml ? `DML:${stats.dml}` : '',
      stats.callouts ? `HTTP:${stats.callouts}` : '',
      stats.exceptions ? `EXC:${stats.exceptions}` : ''
    ].filter(Boolean).join(' ');
    if (counts) labelLines.push(counts);
    if (stats.totalNanos > 0) labelLines.push(`${(stats.totalNanos / 1_000_000).toFixed(0)} ms`);
    if (stats.isTrigger && stats.detail) labelLines.push(`(${escapeMermaidLabel(stats.detail)})`);
    const shape = stats.isTrigger ? `${id}{{"${labelLines.join('<br/>')}"}}` : `${id}["${labelLines.join('<br/>')}"]`;
    lines.push(`  ${shape}`);
    if (stats.exceptions > 0) lines.push(`  class ${id} hasExc;`);
  }
  for (const edge of keptEdges) {
    const fromId = ids.get(edge.from);
    const toId = ids.get(edge.to);
    if (!fromId || !toId) continue;
    const label = edge.count > 1 ? `|x${edge.count}|` : '';
    lines.push(`  ${fromId} -->${label} ${toId}`);
  }
  lines.push('  classDef hasExc fill:#f85149,stroke:#7a1d24,color:#fff;');
  lines.push('```');

  if (droppedNodes > 0 || droppedEdges > 0) {
    const parts: string[] = [];
    if (droppedNodes > 0) parts.push(`${droppedNodes} less-active node${droppedNodes === 1 ? '' : 's'}`);
    if (droppedEdges > 0) parts.push(`${droppedEdges} low-frequency edge${droppedEdges === 1 ? '' : 's'}`);
    lines.push('');
    lines.push(`> _Diagram trimmed for readability: ${parts.join(' and ')} omitted. Raise \`sfLogReader.mermaidMaxNodes\` / \`sfLogReader.mermaidMaxEdges\` to show more._`);
  }
  return lines.join('\n');
}

function topLevelList(frames: Frame[]): string {
  const tops = frames.filter(f => f.parent == null);
  if (tops.length === 0) return '_No top-level frames detected._';
  return tops
    .map((f, i) => {
      const counts = [
        f.soql ? `${f.soql} SOQL` : '',
        f.dml ? `${f.dml} DML` : '',
        f.callouts ? `${f.callouts} callouts` : '',
        f.exceptions.length ? `${f.exceptions.length} exceptions` : ''
      ].filter(Boolean).join(', ');
      const elapsed = f.enteredNanos != null && f.exitedNanos != null && f.exitedNanos > f.enteredNanos
        ? ` — ${((f.exitedNanos - f.enteredNanos) / 1_000_000).toFixed(1)} ms`
        : '';
      const tag = f.isTrigger ? 'trigger' : 'class';
      return `${i + 1}. **${escapeMd(f.className)}** _(${tag}${f.detail ? `, ${escapeMd(f.detail)}` : ''})_${counts ? ` — ${counts}` : ''}${elapsed}`;
    })
    .join('\n');
}

function truncate(s: string, max: number): string {
  if (!s) return '';
  if (s.length <= max) return s;
  return s.slice(0, max) + '…';
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function escapeMermaidLabel(s: string): string {
  return s.replace(/"/g, '\\"').replace(/[\r\n]+/g, ' ');
}
