import { LogCategory, parseLogs, summarize } from './logParser';
import { StoredLogMeta } from './logStore';
import {
  ClassStats,
  DmlOp,
  Frame,
  LimitException,
  LimitMetric,
  MethodCount,
  ObservedCounts,
  SoqlTiming,
  collectDmlBreakdown,
  collectHottestMethods,
  collectLimitExceptions,
  collectObservedCounts,
  collectSoqlTimings,
  computeTotalElapsedMs,
  parseLimits,
  walk
} from './analysisModel';

// Re-exported so existing importers (and tests) keep resolving these from
// summaryGenerator; the implementations now live in analysisModel.
export { parseCodeUnit, extractSoqlFromRaw, parseLimits } from './analysisModel';

export interface SummaryOptions {
  mermaidMaxEdges?: number;
  mermaidMaxNodes?: number;
}

export function generateSummary(meta: StoredLogMeta, body: string, options: SummaryOptions = {}): string {
  const entries = parseLogs(body);
  const stats = summarize(entries);
  const { frames, byClass, edgeCalls } = walk(entries);
  const soqlTimings = collectSoqlTimings(entries);
  const dmlBreakdown = collectDmlBreakdown(entries);
  const hottestMethods = collectHottestMethods(entries, 15);
  const observed = collectObservedCounts(entries, soqlTimings, dmlBreakdown);
  const limits = parseLimits(body);
  const exceptions = entries.filter(e => e.category === 'EXCEPTION');
  const limitExceptions = collectLimitExceptions(entries);
  const totalElapsedMs = computeTotalElapsedMs(entries);

  const lines: string[] = [];
  lines.push(`# Log Summary — \`${meta.Id}\``);
  lines.push('');
  lines.push(metadataBlock(meta, body, totalElapsedMs));
  lines.push('');
  lines.push('## Event counts');
  lines.push(eventCountsTable(stats.byCategory, stats.total));
  lines.push('');
  if (limitExceptions.length > 0) {
    lines.push('## Limit exceptions');
    for (const le of limitExceptions) {
      const at = le.metric && le.value != null && le.cap != null
        ? ` — hit at **${le.value}/${le.cap}** ${escapeMd(le.metric)}`
        : '';
      lines.push(`- \`${escapeMd(le.lineRef)}\` ${escapeMd(le.message)}${at}`);
    }
    lines.push('');
  }
  lines.push('## Observed counts (from log events)');
  lines.push(observedCountsTable(observed, limitExceptions));
  lines.push('');
  if (limits.length > 0) {
    lines.push('## Reported governor snapshot');
    lines.push('_Latest `LIMIT_USAGE_FOR_NS` snapshot SF emitted. This snapshot is written at frame boundaries, so it can lag the **Observed counts** above when the limit is hit inside a tight loop._');
    lines.push('');
    lines.push(limitsTable(limits));
    lines.push('');
  }
  lines.push('## Per-class breakdown');
  lines.push(perClassTable(byClass));
  lines.push('');
  if (dmlBreakdown.length > 0) {
    lines.push('## DML breakdown');
    lines.push(dmlBreakdownTable(dmlBreakdown));
    lines.push('');
  }
  if (soqlTimings.length > 0) {
    lines.push('## Slowest SOQL queries');
    lines.push(soqlTimingTable(soqlTimings.slice(0, 10)));
    lines.push('');
  }
  if (hottestMethods.length > 0) {
    lines.push('## Hottest methods (by entry count)');
    lines.push(hottestMethodsTable(hottestMethods));
    lines.push('');
  }
  lines.push('## Call graph');
  lines.push('');
  lines.push(renderMermaid(byClass, edgeCalls, {
    maxEdges: options.mermaidMaxEdges,
    maxNodes: options.mermaidMaxNodes
  }));
  lines.push('');
  if (exceptions.length > 0) {
    lines.push('## Exceptions');
    for (const e of exceptions) {
      lines.push(`- **${e.eventType}** ${e.lineRef ? `\`${e.lineRef}\`` : ''} — ${truncate(e.message, 400)}`);
    }
    lines.push('');
  }
  lines.push('## Top-level call order');
  lines.push(topLevelList(frames));
  lines.push('');
  lines.push(`<sub>Generated by sf-log-reader on ${new Date().toISOString()}.</sub>`);
  lines.push('');
  return lines.join('\n');
}

function metadataBlock(meta: StoredLogMeta, body: string, totalElapsedMs: number | undefined): string {
  const rows: Array<[string, string]> = [
    ['Org', `\`${meta.orgAlias ?? meta.orgUsername}\``],
    ['User', `${meta.LogUserName ?? '?'} (\`${meta.LogUserId ?? '?'}\`)`],
    ['Operation', meta.Operation ?? '—'],
    ['Application', meta.Application ?? '—'],
    ['Status', meta.Status ?? '—'],
    ['Reported duration', meta.DurationMilliseconds != null ? `${meta.DurationMilliseconds} ms` : '—'],
    ['Elapsed (from log)', totalElapsedMs != null ? `${totalElapsedMs.toFixed(1)} ms` : '—'],
    ['Log size', meta.LogLength != null ? formatBytes(meta.LogLength) : `${body.length} bytes (local)`],
    ['Started at', meta.StartTime ?? '—'],
    ['Fetched at', meta.fetchedAt]
  ];
  const out = ['| Field | Value |', '| --- | --- |'];
  for (const [k, v] of rows) out.push(`| ${k} | ${escapeMd(v)} |`);
  return out.join('\n');
}

function observedCountsTable(c: ObservedCounts, limitExceptions: LimitException[]): string {
  const exMap = new Map<string, LimitException>();
  for (const le of limitExceptions) if (le.metric) exMap.set(le.metric.toLowerCase(), le);
  const lookup = (...keys: string[]) => {
    for (const k of keys) {
      for (const [name, le] of exMap.entries()) if (name.includes(k)) return le;
    }
    return undefined;
  };
  const rows: Array<[string, number, LimitException | undefined]> = [
    ['SOQL queries', c.soqlQueries, lookup('soql queries', 'soql')],
    ['SOQL rows returned', c.soqlRows, lookup('query rows')],
    ['SOSL queries', c.soslQueries, lookup('sosl')],
    ['DML statements', c.dmlStatements, lookup('dml statements')],
    ['DML rows', c.dmlRows, lookup('dml rows')],
    ['Callouts', c.callouts, lookup('callout')],
    ['Async jobs enqueued', c.asyncJobsEnqueued, lookup('async')],
    ['Platform events published', c.publishImmediateEvents, undefined]
  ];
  const visible = rows.filter(([, v, ex]) => v > 0 || ex);
  if (visible.length === 0) return '_No countable events observed._';
  const out = ['| Metric | Observed | Limit hit? |', '| --- | ---: | --- |'];
  for (const [name, value, ex] of visible) {
    const flag = ex
      ? `❌ exceeded${ex.cap != null ? ` (\`${ex.value ?? '?'}/${ex.cap}\`)` : ex.value != null ? ` (at \`${ex.value}\`)` : ''}`
      : '';
    out.push(`| ${escapeMd(name)} | ${value} | ${flag} |`);
  }
  return out.join('\n');
}

function eventCountsTable(byCategory: Record<LogCategory, number>, total: number): string {
  const rows = (Object.entries(byCategory) as Array<[LogCategory, number]>)
    .filter(([, count]) => count > 0)
    .sort((a, b) => b[1] - a[1]);
  if (rows.length === 0) return '_No entries parsed._';
  const out = ['| Category | Count | Share |', '| --- | ---: | ---: |'];
  for (const [cat, count] of rows) {
    const pct = total > 0 ? ((count / total) * 100).toFixed(1) : '0.0';
    out.push(`| ${cat} | ${count} | ${pct}% |`);
  }
  return out.join('\n');
}

function limitsTable(limits: LimitMetric[]): string {
  const out = ['| Metric | Used | Limit | Headroom | Usage |', '| --- | ---: | ---: | ---: | --- |'];
  for (const m of limits) {
    const pct = m.max > 0 ? (m.used / m.max) * 100 : 0;
    const bar = pctBar(pct);
    const headroom = m.max - m.used;
    out.push(`| ${escapeMd(m.name)} | ${m.used} | ${m.max} | ${headroom} | ${bar} ${pct.toFixed(1)}% |`);
  }
  return out.join('\n');
}

function pctBar(pct: number): string {
  const slots = 10;
  const filled = Math.min(slots, Math.round((pct / 100) * slots));
  return '█'.repeat(filled) + '░'.repeat(slots - filled);
}

function perClassTable(byClass: Map<string, ClassStats>): string {
  if (byClass.size === 0) return '_No class/trigger frames detected._';
  const rows = Array.from(byClass.values()).sort((a, b) => {
    const total = (s: ClassStats) => s.soql + s.dml + s.callouts + s.exceptions;
    return total(b) - total(a) || a.className.localeCompare(b.className);
  });
  const out = ['| Class | Kind | Enters | SOQL | DML | Callouts | Exceptions | Time (ms) |',
    '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |'];
  for (const s of rows) {
    const time = s.totalNanos > 0 ? (s.totalNanos / 1_000_000).toFixed(1) : '—';
    out.push(`| ${escapeMd(s.className)} | ${s.isTrigger ? 'trigger' : 'class'} | ${s.enters} | ${s.soql} | ${s.dml} | ${s.callouts} | ${s.exceptions} | ${time} |`);
  }
  return out.join('\n');
}

function dmlBreakdownTable(rows: DmlOp[]): string {
  const out = ['| Op | Type | Statements | Rows |', '| --- | --- | ---: | ---: |'];
  for (const r of rows) {
    out.push(`| ${escapeMd(r.op)} | ${escapeMd(r.type)} | ${r.count} | ${r.rows} |`);
  }
  return out.join('\n');
}

function soqlTimingTable(rows: SoqlTiming[]): string {
  const out = ['| # | Line | Rows | Duration | Query |', '| ---: | --- | ---: | ---: | --- |'];
  rows.forEach((r, i) => {
    const dur = r.durationMs != null ? `${r.durationMs.toFixed(1)} ms` : '—';
    const rows = r.rows != null ? String(r.rows) : '—';
    out.push(`| ${i + 1} | \`${escapeMd(r.lineRef)}\` | ${rows} | ${dur} | \`${escapeMd(truncate(r.query, 160))}\` |`);
  });
  return out.join('\n');
}

function hottestMethodsTable(methods: MethodCount[]): string {
  const out = ['| Method | Calls |', '| --- | ---: |'];
  for (const m of methods) out.push(`| \`${escapeMd(m.signature)}\` | ${m.enters} |`);
  return out.join('\n');
}

interface MermaidOptions {
  maxEdges?: number;
  maxNodes?: number;
}

function renderMermaid(byClass: Map<string, ClassStats>, edgeCalls: Map<string, Map<string, number>>, options: MermaidOptions = {}): string {
  if (byClass.size === 0) return '_(no frames to diagram)_';
  const maxNodes = Math.max(1, options.maxNodes ?? 60);
  const maxEdges = Math.max(1, options.maxEdges ?? 400);

  // Rank classes by activity so we drop the least useful first.
  const activity = (s: ClassStats) =>
    s.enters + s.soql * 2 + s.dml * 2 + s.exceptions * 3 + s.callouts * 2;
  const ranked = Array.from(byClass.values()).sort((a, b) => activity(b) - activity(a));
  const totalNodes = ranked.length;
  const keptNodes = ranked.slice(0, maxNodes);
  const droppedNodes = totalNodes - keptNodes.length;
  const kept = new Set(keptNodes.map(s => s.className));

  // Flatten edges (only between kept nodes), rank by call count desc.
  type EdgeRec = { from: string; to: string; count: number };
  const allEdges: EdgeRec[] = [];
  for (const [from, tos] of edgeCalls.entries()) {
    if (!kept.has(from)) continue;
    for (const [to, count] of tos.entries()) {
      if (!kept.has(to)) continue;
      allEdges.push({ from, to, count });
    }
  }
  allEdges.sort((a, b) => b.count - a.count);
  const keptEdges = allEdges.slice(0, maxEdges);
  const droppedEdges = allEdges.length - keptEdges.length;

  const ids = new Map<string, string>();
  let counter = 0;
  for (const s of keptNodes) ids.set(s.className, `n${counter++}`);

  const lines: string[] = ['```mermaid'];
  if (maxEdges > 0) lines.push(`%%{init: {"maxEdges": ${maxEdges}}}%%`);
  lines.push('flowchart TD');
  for (const stats of keptNodes) {
    const id = ids.get(stats.className)!;
    const labelLines: string[] = [escapeMermaidLabel(stats.className)];
    const counts = [
      stats.soql ? `SOQL:${stats.soql}` : '',
      stats.dml ? `DML:${stats.dml}` : '',
      stats.callouts ? `HTTP:${stats.callouts}` : '',
      stats.exceptions ? `EXC:${stats.exceptions}` : ''
    ].filter(Boolean).join(' ');
    if (counts) labelLines.push(counts);
    if (stats.totalNanos > 0) labelLines.push(`${(stats.totalNanos / 1_000_000).toFixed(0)} ms`);
    if (stats.isTrigger && stats.detail) labelLines.push(`(${escapeMermaidLabel(stats.detail)})`);
    const shape = stats.isTrigger ? `${id}{{"${labelLines.join('<br/>')}"}}` : `${id}["${labelLines.join('<br/>')}"]`;
    lines.push(`  ${shape}`);
    if (stats.exceptions > 0) lines.push(`  class ${id} hasExc;`);
  }
  for (const edge of keptEdges) {
    const fromId = ids.get(edge.from);
    const toId = ids.get(edge.to);
    if (!fromId || !toId) continue;
    const label = edge.count > 1 ? `|x${edge.count}|` : '';
    lines.push(`  ${fromId} -->${label} ${toId}`);
  }
  lines.push('  classDef hasExc fill:#f85149,stroke:#7a1d24,color:#fff;');
  lines.push('```');

  if (droppedNodes > 0 || droppedEdges > 0) {
    const parts: string[] = [];
    if (droppedNodes > 0) parts.push(`${droppedNodes} less-active node${droppedNodes === 1 ? '' : 's'}`);
    if (droppedEdges > 0) parts.push(`${droppedEdges} low-frequency edge${droppedEdges === 1 ? '' : 's'}`);
    lines.push('');
    lines.push(`> _Diagram trimmed for readability: ${parts.join(' and ')} omitted. Raise \`sfLogReader.mermaidMaxNodes\` / \`sfLogReader.mermaidMaxEdges\` to show more._`);
  }
  return lines.join('\n');
}

function topLevelList(frames: Frame[]): string {
  const tops = frames.filter(f => f.parent == null);
  if (tops.length === 0) return '_No top-level frames detected._';
  return tops
    .map((f, i) => {
      const counts = [
        f.soql ? `${f.soql} SOQL` : '',
        f.dml ? `${f.dml} DML` : '',
        f.callouts ? `${f.callouts} callouts` : '',
        f.exceptions.length ? `${f.exceptions.length} exceptions` : ''
      ].filter(Boolean).join(', ');
      const elapsed = f.enteredNanos != null && f.exitedNanos != null && f.exitedNanos > f.enteredNanos
        ? ` — ${((f.exitedNanos - f.enteredNanos) / 1_000_000).toFixed(1)} ms`
        : '';
      const tag = f.isTrigger ? 'trigger' : 'class';
      return `${i + 1}. **${escapeMd(f.className)}** _(${tag}${f.detail ? `, ${escapeMd(f.detail)}` : ''})_${counts ? ` — ${counts}` : ''}${elapsed}`;
    })
    .join('\n');
}

function truncate(s: string, max: number): string {
  if (!s) return '';
  if (s.length <= max) return s;
  return s.slice(0, max) + '…';
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function escapeMermaidLabel(s: string): string {
  // Mermaid does NOT honor backslash-escaped quotes inside ["..."] labels, and
  // " [ ] { } | ; < > terminate or corrupt the label — replace them with safe
  // equivalents so a class/trigger name containing them can't break the diagram.
  return s
    .replace(/[\r\n]+/g, ' ')
    .replace(/"/g, "'")
    .replace(/[<>]/g, '')
    .replace(/[\[\]{}|;]/g, ' ')
    .trim();
}
